export interface FilterModel {
    inquiryID?: any;
    commodity?: any;
    inquiryType?: any;
    client?: any;
    pol?: any;
    pod?: any;
    createdBy?: any;
    sentTo?: any;
    termofService?: any;
    dateCreate?: any;
}

export interface RcFclFilterModel {
    pricingID?: any;
    creator?: any;
    dateCreate?: any;
    dateModify?: any;
    portofLoading?: any;
    portofDischarge?: any;
    transitPort?: any;
    carrierID?: any;
    importMode?: any;
    freightChargeLCL?: any;
    minimumChargeLCL?: any;
    container20?: any;
    container40?: any;
    container45?: any;
    containerHC?: any;
    others?: any;
    subCharge1?: any;
    subCharge2?: any;
    subCharge3?: any;
    containerType?: any;
    currency?: any;
    includeAddon?: any;
    emptyReturn?: any;
    transitTime?: any;
    frequency?: any;
    cutOff?: any;
    notes?: any;
    validDateFrom?: any;
    validDateTo?: any;
    remarks?: any;
    isLCL?: any;
    isPublic?: any;
    customsClearanceAtDestination?: any;
    customsClearanceAtOrigin?: any;
}

export interface TruckingChargeFilterModel {
    pricingID?: any;
    creator?: any;
    dateCreate?: any;
    dateModify?: any;
    pickupCity?: any;
    pickupArea?: any;
    deliveryCity?: any;
    deliveryArea?: any;
    truck20?: any;
    truck40?: any;
    truck500kgs?: any;
    truckTonLevel1?: any;
    truckTonLevel2?: any;
    truckTonLevel3?: any;
    truckTonLevel4?: any;
    truckTonLevel5?: any;
    truckTonLevel6?: any;
    truckTonLevel7?: any;
    truckTonLevel8?: any;
    truckTonLevel9?: any;
    truckTonLevel10?: any;
    truckTonLevel11?: any;
    truckTonLevel12?: any;
    truckTonLevel13?: any;
    truckTonLevel14?: any;
    truckTonLevel15?: any;
    truckTonLevel16?: any;
    notes?: any;
    freeDetentionTime?: any;
    detentionCharge?: any;
    validDateFrom?: any;
    validDateTo?: any;
    updatedBy?: any;
    currency?: any;
}

export interface LocalChargeFilterModel {
    pricingID?: any;
    creator?: any;
    dateCreate?: any;
    dateModify?: any;
    portofLoading?: any;
    portofDischarge?: any;
    transitPort?: any;
    notes?: any;
    service?: any;
    validDateFrom?: any;
    validDateTo?: any;
    updatedBy?: any;
}

export interface RcCustomsClearanceFilterModel {
    pricingID?: any,
    creator?: any,
    dateCreate?: any,
    dateModify?: any,
    terminal?: any,
    purposeOfImEx?: any,
    channel?: any,
    min?: any,
    container20?: any,
    container40?: any,
    lcl?: any,
    air?: any,
    currency?: any,
    excludedCommodity?: any,
    notes?: any,
    service?: any,
    fee?: any,
    unit?: any,
    companyID?: any,
    validDateFrom?: any,
    validDateTo?: any,
    updatedBy?: any,
    type?: any,
    carrier?: any
}

export interface QuotationFilterModel {
    _id?: any;
    quotationNo?: any;
    client?: any;
    creator?: any;
    dateCreate?: any;
    dateModify?: any;
    quotationDate?: any;
    termofService?: any;
    commodity?: any;
    hsCode?: any;
    sentTo?: any;
    pickupAt?: any;
    deliveryTo?: any;
    deadlineDelivery?: any;
    volume?: any;
    volumeUnit?: any;
    quantity?: any;
    dimensions?: any;
    grossWeight?: any;
    palletizedPackage?: any;
    nonPalletPackageQuantity?: any;
    truckingVolumeGrossWeight?: any;
    isExport?: any;
    clearanceTerminal?: any;
    purposeOfImEx?: any;
    specialRequirements?: any;
    targetedRateAndCharges?: any;
    blFee?: any;
    thcOrigin?: any;
    cfsOrigin?: any;
    telexRelease?: any;
    doFee?: any;
    thcDestination?: any;
    cfsDestination?: any;
    handlingFee?: any;
    containerCleaningFee?: any;
    cic?: any;
    awb_SET?: any;
    ams_HBL?: any;
    ams_MBL?: any;
    terminalCharge_KG?: any;
    xray_KG?: any;
    laborCharge?: any;
    currency?: any;
    customsClearanceAtOrigin?: any;
    customsClearanceAtDestination?: any;
    cargoIsUnstackable?: any;
    packageCanBeTilted?: any;
    needExpressService?: any;
    remarks?: any;
    quotationType?: any;
    saveDraft?: any;
    logInfo?: any;
    cargoReadyDateTo?: any;
    cargoReadyDateFrom?: any;
}

export interface BookingFilterModel {
    _id?: any;
    bookingNo?: any;
    dateMaking?: any;
    revision?: any;
    creator?: any;
    cancelBooking?: any;
    releaseNo?: any;
    attn?: any;
    saleman?: any;
    shipmentType?: any;
    shipperID?: any;
    shipperInfo?: any;
    consigneeID?: any;
    consigneeInfo?: any;
    nominatedPartyID?: any;
    nominatedContainers?: any;
    dateofStuffingStart?: any;
    dateofStuffingEnd?: any;
    placeofStuffing?: any;
    contact?: any;
    closingTimeDate?: any;
    forwardingAgent?: any;
    portofLoading?: any;
    portofDischarge?: any;
    carrier?: any;
    estimatedVessel?: any;
    etd?: any;
    eta?: any;
    quantity?: any;
    commodity?: any;
    grossWeight?: any;
    cbm?: any;
    specialRequest?: any;
    emptyReturnDate?: any;
    operationCode?: any;
    portofTransit?: any;
    placeofDelivery?: any;
    paymentTerm?: any;
    serviceMode?: any;
    freightRate?: any;
    otherInfo?: any;
    hblNo?: any;
    noofHBL?: any;
    freeDem?: any;
    freeDet?: any;
    referenceNo?: any;
    pickupAt?: any;
    pickupDate?: any;
    dropoffAt?: any;
    dropoffDate?: any;
    transactionID?: any;
    remark?: any;
    bkApp?: any;
    bkAppDate?: any;
    bkAppBy?: any;
    bkAppComment?: any;
}